### ISSUE TITLE
Links are incorrect on gallery page

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#14]
The links in the top nav are not correctly linked to their correct sections. If you go to the gallery page, and then click on the nav at the top (like "events" or "contact"), it'll just take you to the top of the home page and not the correct section. 

Please link them to their correct anchors

due:
8-11-15   11a

**Comment by vanderbeam** [comment]
I fixed this and the code is correct in the github repo, but it's not showing up in the gh-pages. Unsure if it just hasn't loaded yet or what bu I'm looking into it.

**Comment by vanderbeam** [comment]
OK it's good now

**Comment by rodneystrong** [comment]
Yep, it's good. thanks!
