### ISSUE TITLE
horizontal sidebar issue

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#16]
For some reason the site has a horizontal sidebar. Please adjust your code so the user doesn't have to scroll sideways in addition to scrolling vertically

![screen shot 2015-08-13 at 12 37 34 pm](https://cloud.githubusercontent.com/assets/539962/9259848/0b93f1e2-41b9-11e5-9661-e5a2f0a0e865.png)

due: 

8-13-15  5p

**Comment by vanderbeam** [comment]
Done. 

After coming to several dead ends and frustrating attempts to fix it I realized it was fine before I edited the newsletter input field. Long story short, that was issue. And it's fixed now.

**Comment by rodneystrong** [comment]
nice! good job!
