### ISSUE TITLE
Add new events from current live site

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#17]
Go to this link and add the new events she's posted to the gh-pages site: http://www.sublimetimefun.com/#!events/ct1b

due:
8-20-15  6p

**Comment by vanderbeam** [comment]
All set EXCEPT, there are two listed at the bottom of the live site I didn't add because they have backdates. I wasn't sure if maybe she copied and pasted them and forgot to change the dates or if they never got removed.... regardless, I didn't add them. Let me know if you want me to.

**Comment by rodneystrong** [comment]
excellent work!
