### ISSUE TITLE
Update class info

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#20]
Remove the outdated classes and put in the new classes that are on this site: 
https://squareup.com/market/sublimetimefun

due:
9-15-15  5p

**Comment by vanderbeam** [comment]
Do I need login info for this?

**Comment by rodneystrong** [comment]
No, sorry it wasn't clear. 

I meant, you need to put the new classes onto the gh-pages branch of the code.

**Comment by rodneystrong** [comment]
Meg, how we doin on this? Is anything still unclear about what I'm askin? 

If possible, could this get done today by 5p?

**Comment by vanderbeam** [comment]
I commented out the times and addresses because they're not longer on the website. let me know if you want me to put them back

**Comment by rodneystrong** [comment]
I just double-checked the Square site and it turns out she DOES include the address still.. Can you tell me how you got the impression that she doesn't? 

Here's a screenshot of what I'm seeing for the event on the 24th:

![screen shot 2015-09-16 at 3 16 26 pm](https://cloud.githubusercontent.com/assets/539962/9920082/1350965a-5c86-11e5-9844-2a06443d9435.png)


Please go back through all the events on her Square page and include the appropriate image and address onto her site.

due:
9-16-15   7p

**Comment by rodneystrong** [comment]
Also, please FTP this to the live site

**Comment by vanderbeam** [comment]
@rodneystrong I haven't updated the FTP site but sublimetimefun.com doesn't show live. Is it not up yet?

**Comment by rodneystrong** [comment]
? Really? it's live for me.. @AaronAguilar @jperez4509 @purplyrocky could you please visit sublimetimefun.com and comment here if you see the site we created for her? 

Also, @vanderbeam can you log in and see the sublimetimefun.com folder? Please check thoroughly and comment here if you can/can't see it

**Comment by jperez4509** [comment]
@rodneystrong @vanderbeam I just visited the site and it is live.

**Comment by vanderbeam** [comment]
@rodneystrong I'm still getting the time out error. On my phone, too. I have access to the FTP but I'm uneasy about updating it when I can't check the live site.

**Comment by purplyrocky** [comment]
Just checked on my phone, it's up and running

**Comment by rodneystrong** [comment]
Hmmm ok, I'll reassign this to someone where the live site is working.

@purplyrocky , Meg already updated the gh-pages branch so all you should need to do is FTP that branch onto the live folder. 

However, please go the the beginning of this issue (the description) and double-check everything to be correct before you upload to FTP. 

due:
9-17-15   9p

**Comment by purplyrocky** [comment]
@rodneystrong i'll be able to do this at noon during lunch. I have already cloned the repo but since I am on a new laptop, I do not have Firezilla installed. Which program should i install? Then, i'll need you to share the login info in lastpass, please.

**Comment by rodneystrong** [comment]
@purplyrocky perfect. here's the link to get filezilla for mac: https://filezilla-project.org/download.php?type=client

it should operate pretty much the same way as it does for windows (same interface and all that jazz)

I'll share the FTP creds through lastpass right now. email me right away if you don't get an email notification from lastpass by 11:50a please

**Comment by rodneystrong** [comment]
Raquel, I just checked and it turns out you already accepted the lastpass creds for this. All you'll need to do is log into lastpass and look for media template FTP (or some combination of those words). 

Again, email me or call me right away if something stops you from starting this at 12p

**Comment by purplyrocky** [comment]
@rodneystrong I was just about to reply and say that if I can use firezilla on mac, I will still have the creds from when you sent them a while back but you figured that out before I could say anything.

I've got firezilla installed. Now if i can just remember my password for lastpass....

**Comment by purplyrocky** [comment]
Done
