### ISSUE TITLE
Add images and rearrange

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#21]
Client wants to organize the gallery page into sections as follows:

Row 1 through 16 should be in **Sublime Time Experience**
Row 17 can be taken out (girl with rainstick, owl in colored pencil, white clay skull, clay whistles)
The rest can be put into **Custom Artwork**

The words in bold should be the headings of the sections.

due:
10-2-15  12p

**Comment by AaronAguilar** [comment]
Updated headers: http://editllc.github.io/client-sublime-time/gallery.html

Used the same background as the navigation 'cause it pops out more to the user. 

I'll FTP in a few--

Just saying, but I think that it would be better if there were albums with titles on the Gallery page, that linked to other pages, if she plans to upload more images and events. It'll also lower the load time of having so many images on one page.

**Comment by rodneystrong** [comment]
Oh nice, good call. 

We may end up going with your suggestion about separate pages, but please upload what you have now.

**Comment by rodneystrong** [comment]
this was done right?

i checked the site and it looks correct but i wanted to double-check with you in case there was something you know that was missing.

**Comment by AaronAguilar** [comment]
Yeah this is done.

**Comment by rodneystrong** [comment]
Good stuff
