### ISSUE TITLE
Add Images to the site

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#22]
Remember to crop the thumbnails so they don't look distorted.

The folders are in the google drive and they are organized in the way they should be displayed on the page. For example, there's a folder titled "Custom Artwork" so all those images should go under a section on the site that says "Custom Artwork". If the section doesn't exist then please create it and place the photos accordingly.

due:
10-3-15   12p

**Comment by AaronAguilar** [comment]
There's nothing in the "Custom Artwork" folder?
https://drive.google.com/folderview?id=0B_CwDsLo9u8NfkJmSFhzb2VaQ1JZQThta0NZbWJyZTVJVEVKdzdzaU1saE93UjBuT0pBdkU&usp=sharing

**Comment by rodneystrong** [comment]
Yea, I noticed that. Follow up with client and we'll see.

**Comment by rodneystrong** [comment]
Actually there is now, check it.

**Comment by AaronAguilar** [comment]
Apologies -- I've uploaded the new images and added alt tags for all images, included those on the home page. I also linked the logo to the home page.

http://editllc.github.io/client-sublime-time/gallery.html
