### ISSUE TITLE
Add video to site

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#23]
Client trusts us on the best place to put the video. 

Where do you think we can add this video? 

````<iframe width="560" height="315" src="https://www.youtube.com/embed/N7lSJpnFCTU" frameborder="0" allowfullscreen></iframe>````

due:
10-4-15    3p

**Comment by AaronAguilar** [comment]
Hey -- 

I was wondering, is it better if I make a News/Blog section on the page like I've done with HPC? I noticed she posted the same thing on her Facebook, so she might keep wanting to add new things in the future.

**Comment by AaronAguilar** [comment]
Did it: 
http://editllc.github.io/client-sublime-time/index.html

The client could post the blog post on Faceboook and the links on the news section link to the Facebook post.

**Comment by rodneystrong** [comment]
I LOVE IT!  Good work, well executed.
