### ISSUE TITLE
Old Event's Removed?

### ISSUE THREAD

**Issue by rcsargent** [EditLLC/client-sublime-time#26]
http://sublimetimefun.com/ 

What's the process for removing these event's after they have passed? 
- Suggestion make two github issues, one to put up and take down.

**Comment by rodneystrong** [comment]
Good call, I'll also ping the client to see if she wants to do something different in terms of how soon we remove the old events.

I agree, 2 issues to put up and put down.

**Comment by rcsargent** [comment]
Hard part will be tracking those issues to make sure they're done

**Comment by rodneystrong** [comment]
she confirmed wanting old events removed the day after
