### ISSUE TITLE
Please remove old events

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#27]
Any event that is already passed, please remove it and FTP the changes.

due:
10-22-15    5p

**Comment by vanderbeam** [comment]
@rodneystrong There's only one events listed now. Are there any new upcoming ones I should add while I'm in the file?

**Comment by rodneystrong** [comment]
Nope, thanks for checkin though.

**Comment by vanderbeam** [comment]
All set then.
The next and last event is on the 24th. Want me to set an alarm on my phone and take it down on the 25th and post something like "There are no upcoming events at this time. Please check back again soon!"

**Comment by rodneystrong** [comment]
you read my mind meg. please do.
