### ISSUE TITLE
Next event

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#28]
>  I have a new date to add to the page......I will hopefully have some more to add soon I just need to paint the examples so there will be an image
Thank you :)
Ticket url : https://squareup.com/market/sublimetimefun/sublime-time-experience-1
Thursday - November 5
Sublime Time Experience - Sugar Cat
Have a great night!

due:
11-2-15  10am

**Comment by vanderbeam** [comment]
All set

**Comment by rodneystrong** [comment]
The event just passed, so go ahead and remove it.

**Comment by vanderbeam** [comment]
Done

**Comment by rodneystrong** [comment]
Excellent, i also like how you put some text in to explain the absence of classes.
