### ISSUE TITLE
Add this event

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#29]
URL is sublimetimefun.com 

FTP into our buildicus server, copy/paste the code from that domain. Open the index.html file and then look for the "events" section. You should find an event that's already commented out; @vanderbeam did a good job of leaving a pre-built layout. All you'll need to do is copy/paste that commented event, uncomment it, and then fill in the relevant info below in the right spots. 

Hi there :)  I will be adding a date.......
Sublime Time Angel
November 19 6-8pm 
$35/person 

the ticket url:  https://squareup.com/market/sublimetimefun/sublime-time-experience

Here's the image:
![2 hour painting angel](https://cloud.githubusercontent.com/assets/539962/11160637/57124cda-8a21-11e5-8749-e7cd4e0cfa65.jpg)

Be sure to rotate that image.

due:
11-13-15   5p

**Comment by rampage1213** [comment]
Done!

**Comment by rodneystrong** [comment]
Unfortunately, the image link is broken. Please view the live site, understand what's happening, and then fix the issue.

**Comment by rampage1213** [comment]
All done found that well going thought inspect elements that the image didn't have permissions so in filezilla I had to change to the unix permissions so that the group and world could be read

**Comment by rodneystrong** [comment]
good work! please re-read your comment correct any grammatical and usage errors.

**Comment by rampage1213** [comment]
This task is all done. I ran into a problem with unix permissions on filezilla turns out that it didn't have the read permission turned on by default so i had to check it to be read so that on the live site it would load. so if there is a issue in the future remember to give it the unix permissions to be read by all the groups.
