### ISSUE TITLE
Fix links for all 'buy now' buttons

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#3]
![tickets](https://cloud.githubusercontent.com/assets/539962/8920395/614972fe-347d-11e5-8e57-ea3ca5e33857.jpg)

Please fix all the button links to go to the correct places

due date:
7-28-15  5p

**Comment by vanderbeam** [comment]
Done

**Comment by rodneystrong** [comment]
Excellent job!
