### ISSUE TITLE
Add the snowman event

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#30]
Hello Alex I have another date set :)
Dec 3rd 5:30-7:30pm at the studio
Sublime Time Art Hop Snowman

​Ticket url:
https://squareup.com/market/sublimetimefun/sublime-time-nd-saturday
Thank you :)

https://drive.google.com/file/d/0B_CwDsLo9u8NSE56YWk0NXE4QjA/view?usp=drive_web

due:
11-17-15   5p

**Comment by vanderbeam** [comment]
Done
