### ISSUE TITLE
Remove "by buildicus" branding at bot of site

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#31]
due:
11-17-15    5p

**Comment by vanderbeam** [comment]
Done but not commited to gthub. HAd to just go through the ftp because my gitbash isn't working for some reason or another.

**Comment by rodneystrong** [comment]
When can you get this pushed to github?

**Comment by vanderbeam** [comment]
Got it to push

**Comment by rodneystrong** [comment]
For posterity's sake, please explain the issue you had here.

**Comment by rodneystrong** [comment]
Follow up. Please comment here Meg

**Comment by vanderbeam** [comment]
Oh I must not have seen this. I was having issue with Git Bash for about a day. It would work. I don't remember the details.
