### ISSUE TITLE
Make changes to contact form

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#32]
This will be slightly challenging to understand, but not do; there's a 6/10 chance you'll need to ask for help *understanding* this. 

Look at my last commits for the Wise Scuba repo that pertain to the contact form. 

First, set it so the form emails your address, and then implement all the other changes I did for the contact form. 

Once you finish this, please schedule a time to discuss this with me. 

due:
11-19-15   3p

updated due:
12-3-15  3p

**Comment by rodneystrong** [comment]
Meg, what happened here. We've passed the due date again.

**Comment by vanderbeam** [comment]
Let's talk about this this afternoon.

**Comment by rodneystrong** [comment]
@vanderbeam  please comment here what you learned about the code specifically and what investigative techniques you'll use when reverse-engineering future code.

Also, please paste the full commit hash (SHA) that fixed the issue here. Bonus points if you figure out what the hell that means on your own. 

After that, feel free to close the issue.

due:
12-16-15    12p

**Comment by vanderbeam** [comment]
I learned to pay closer attention to what's going on with with GitHub, which even after I got all of the code in, not noticing the subtle comment out in the history caused me much of the stress. I'll double-check the source files the code is calling and whether or not they've been implemented. 

Here's the SHA: 3205aefd1094d8107d41542e3f8a8dd749739ef1
