### ISSUE TITLE
Add this to the site

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#33]
Quintin, work with @jperez4509 for 40 minutes and come  up with a simple way to display the content below. Think of yourself as being a business owner and wanting your customers to take advantage of the offers below for Christmas. 

Off the top of my head I'm thinking you should put this right above the "What is Sublime Time" section and right below the Social media Icons. 

Hi Alex, I would like to add these to the site if possible......
Gift Certificates - 
$35 two hour class url = https://squareup.com/market/sublimetimefun/gift-certfificate 
 $45 three hour class url = https://squareup.com/market/sublimetimefun/gift-certificate 
and a note that says if they would like a specific/custom amount to contact me by email

Custom Mini Paintings - Choose your subject, style and background color $35 each includes mini easel - Makes a great gift! 
url = https://squareup.com/market/sublimetimefun/mini-paintings

due:
12-1-15     5p

**Comment by rampage1213** [comment]
This is all done! Had merge issues with meg be that is all fixed she had to pull and push her code on gh-pages then when I went to merging gh-pages to master some conflicts happened so i had to delete old code. Now master and gh-pages are all up to date and i also FTP.

**Comment by rodneystrong** [comment]
excellent, thank you. props to both you and @vanderbeam for pair-programming the issue out.
