### ISSUE TITLE
Add the next event

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#34]
Just like last time @rampage1213 

Hi Alex,
  Can you please add this event to the  page :)
Sublime Time Santa 
December 10, 2015
6pm-8pm
ticket url:  https://squareup.com/market/sublimetimefun/sublime-time
Thank you :)

due:
12-3-15   4p

**Comment by rampage1213** [comment]
This is all done! gh-pages and master are up to date and ftp.
