### ISSUE TITLE
Add reindeer event: due 12-7-15 6p

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#35]
Hello....here is a new event for the page :)  
December 17, 2015
6:00-8:00pm at the studio
Rudolph​
https://squareup.com/market/sublimetimefun/sublime-time-nd-saturday

![2 hour painting rudolph](https://cloud.githubusercontent.com/assets/539962/11640282/a805a92a-9ce6-11e5-8c67-735be9da6ddf.jpg)

due:
12-7-15     6p

**Comment by rampage1213** [comment]
Done!
