### ISSUE TITLE
remove snowman event

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#36]
As the title states. 

due:
12-7-15    8p

updated due:
12-15-15      12p

**Comment by rampage1213** [comment]
Done!

**Comment by rodneystrong** [comment]
Excellent work. 
As an added bonus (and if you care about the quality of your work), feel free to change the HTML to make the events centered when there aren't 3 to fill up a whole row. 

Notice right now how there's only two events and they look off-center/left-aligned? What quick fix could you make so that they look more justified? 

Comment here before you change the code so I can approve it.

due:
12-15-15      12p

**Comment by rampage1213** [comment]
Ok will do all I have to do is change the columns row to be 6 instead of 4 and it should look great

**Comment by rampage1213** [comment]
Done!
