### ISSUE TITLE
Add video to site

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#37]
Check out this issue for review: https://github.com/EditLLC/client-sublime-time/issues/23

Now go to sublimetimefun.com and go to the "News" section. Look at how @AaronAguilar implemented the videos into the news section as well as linked up the title of each news post and placed a "read more" link as well. 

This is the facebook page: https://www.facebook.com/sublimetimefun/?fref=nf 

This is the exact video I need you to put in the news item: https://youtu.be/axDG47eHHXQ

Again, be sure to look at how the previous developer implemented the news items and try to replicate that method. 

There are currently 2 news items, if you put in a 3rd, you'll notice that there isn't enough room. What would you think is best to do in this case? I already have an idea of what I'd like you to do, but I also want you think to give your opinion as well. 

due: 
12-14-15   7p

**Comment by jarantfos** [comment]
Added video by setting news items to have a column size of 4 - if there are 4 items added, I can set each item to 6, if there are 5 items added, I can have 3 col-4s on the top and 2 col-6s on the bottom, etc..
