### ISSUE TITLE
Old events on http://sublimetimefun.com/

### ISSUE THREAD

**Issue by rcsargent** [EditLLC/client-sublime-time#39]
They still have events from December 10th and 17th on the website

due:
12-22-15   10p

**Comment by rodneystrong** [comment]
Thanks for the heads up richard. 

quintin, please handle this.

due:
12-22-15   10p

**Comment by rampage1213** [comment]
Done!

**Comment by rodneystrong** [comment]
Sorry quintin, but could you please FTP these changes?

**Comment by rampage1213** [comment]
@rodneystrong this is FTP and the live site is up to date

**Comment by rodneystrong** [comment]
Sorry, was it already FTP'ed when you closed it? I may have had a cached version on my browser then. I see it now after refreshing.

**Comment by rampage1213** [comment]
Yes it was FTP'ed when I closed It

**Comment by rodneystrong** [comment]
gotcha, apologies quintin. thanks for doing that.
