### ISSUE TITLE
Spacing on "events" section

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#4]
![space](https://cloud.githubusercontent.com/assets/539962/8943888/191ae610-3532-11e5-839c-07532bda1b95.jpg)

Please fix the spacing to be similar to the other sections on the site. 

due date:
7-28-15  5p

**Comment by vanderbeam** [comment]
Done.

**Comment by rodneystrong** [comment]
Good work Megan!
