### ISSUE TITLE
Add all her events

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#40]
Go to her facebook page: https://www.facebook.com/sublimetimefun

She's got ~8 events posted. Same drill as before; put them up onto the website. Be sure to go to her Square site too to get the correct link for each event. 

Also, time yourself from start to finish on this task and then comment here how long it took. This'll be a good measurement for how long it takes to put up an event in general for her.

due:
12-28-15   5p

**Comment by rampage1213** [comment]
Done! FTP took about 50mins

**Comment by rodneystrong** [comment]
Nice, so a little over 6 minutes per event which includes double-checking the links and FTP'ing.

**Comment by rodneystrong** [comment]
@EditLLC/marketing Richard could you post here what tool you use to stay updated with her facebook events? Or do you manually check her facebook account everyday?

**Comment by rcsargent** [comment]
Hootsuite :)

**Comment by rodneystrong** [comment]
Perfect, thanks @EditLLC/marketing 

Hmm.. @jperez4509 and @rampage1213 please create hootsuite accounts. I'm going to put all of us in charge of monitoring her facebook account and automatically adding her events she posts there.

**Comment by jperez4509** [comment]
@rodneystrong I just created a Hootsuite account and have added Sublime Time to a stream.

**Comment by rampage1213** [comment]
@rodneystrong I also made a Hootsuite account and added Sublime Time to a stream

**Comment by rodneystrong** [comment]
@rampage1213 @jperez4509  you two are awesome, thank you
