### ISSUE TITLE
Create another section

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#42]
She would like a link to her Square store. I initially imaged it being another section on the home page as as a callout to her online store with a button to click. But @jperez4509 might have a better idea on how to incorporate this. 

Please have a mini-discussion with Joel on the best way to implement this design-wise and then code it yourself. 

Here's the link to her Square shop: https://squareup.com/market/sublimetimefun

due:
1-6-15  4p

**Comment by jarantfos** [comment]
I did it my way without consulting Joel, but I'll stop by the office tomorrow and see what he has to say.

**Comment by jperez4509** [comment]
@jarantfos: I wont be in the office today. However, I do have some suggestions for the section. I just saw where you placed it. I think the section needs to be seen as a CTA (call to action) section and should be placed before the events section. It should also grab more attention. A nice subtle way of doing this is maybe creating a nice simple parallax affect similar to the 'Like Us on Facebook' section on Pumpkin King Fresno. http://www.pumpkinsfresno.com/

**Comment by jarantfos** [comment]
Alright, I'll do that. Thanks!

**Comment by rodneystrong** [comment]
Unfortunately the link is wrong. Please go back and fix the link to the square marketplace. It should link to the same link in this issue description. https://squareup.com/market/sublimetimefun

**Comment by jarantfos** [comment]
Whoops, I'll fix that

**Comment by jarantfos** [comment]
Fixed and ftp'd
