### ISSUE TITLE
Add times to the events

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#46]
From the client:

>Thank you so much for getting my events up.....Can you add the times to them too.......They all start at 6pm-8pm accept January 7 and February 4 are 5:30-7:30pm....
Thank you so much :)
​Have a great night!​

Put them right underneath the date

due:
1-2-16   5p

**Comment by rodneystrong** [comment]
Thanks for takin care of this. 

I forgot to mention that any changes you make to the gh-pages branch should also be FTP'ed to the live site (this goes for all our projects that are live with a domain). 

When you can, please FTP your changes to sublimetimefun.com

**Comment by jarantfos** [comment]
Alright, everything is FTP'd
