### ISSUE TITLE
Add her new events from Facebook

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#48]
She just added 6 events. Get them up and posted.

Jan 29 - Cherry Blossoms + Dragonflies

Jan 30 - Fatte Alberts

Feb 18 - Peacock

Feb 26 - Unicorn

Mar 03 - Art Hop

Mar 11 - Lady in the rain

due:
1-8-16    7p

updated due:
1-12-16 3p

**Comment by rampage1213** [comment]
Done! So she doesn't have a Cherry Blossoms + Dragonflies for Jan 29 on her square store she just has one for Jan 7 so I linked that one. Art Hop Mar 03 is not on her square store, I added it to her site it just needs the link.

**Comment by rodneystrong** [comment]
Turns out the buddha link is waaaay down at the bottom of the square page. You'll see it. Be sure to link that up. 

Also, the peacock event is from 6 - 8pm

The Jan 29 isn't on there, you're right. I emailed the client about that. 

due:
1-12-16  3p

**Comment by rampage1213** [comment]
Done!
