### ISSUE TITLE
Implement the single button for all events

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#5]
You made a suggestion to have a single button for all the events and link it to the directory for her squareup site. 

Please implement that in a new branch titled "feature-single-button"

due date:
7-29-15   3p

**Comment by vanderbeam** [comment]
Done. Branch events-1-btn

**Comment by rodneystrong** [comment]
Unfortunately the branch isn't visible here on github. Did you push it?

**Comment by rodneystrong** [comment]
Good work Megan. I like it. 

I'll present it to the Denine as another option.
