### ISSUE TITLE
Add video to the "Meet the founder" section

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#6]
Please add this video underneath the text in the appropriate section:
http://www.youtube.com/watch?v=QIsTRx2cbi0&authuser=0

Make sure it has the correct bootstrap responsive class as well.

due date:
8-3-15   5p

**Comment by vanderbeam** [comment]
I did this Alex. And it looks like you were right, the "one button" mod never got pushed. The video and single button are both available under the "events-1-btn" branch.

**Comment by rodneystrong** [comment]
Great! Could you also please add the video to the gh-pages branch as well? 

Thanks!

due:
same

**Comment by vanderbeam** [comment]
Done.

**Comment by rodneystrong** [comment]
Hey @vanderbeam , sorry I wasn't clear on this, but the video needed to go underneath the text on the right, not replace the picture on the left. 

When you can, please put the picture back in and place the video underneath the text description on the right. Thanks!

due: 
8-4-15  10p

**Comment by vanderbeam** [comment]
Sorry for the miscommunication! I fixed it.

**Comment by rodneystrong** [comment]
Wow nice!  Thanks for that, and no worries dude, it was my bad.
