### ISSUE TITLE
Add GA code to all pages

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-sublime-time#7]
Please add this right before the closing ````</body>```` tag to all the pages:

````
<script>

(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){

(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),

m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)

})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-65222806-1', 'auto');

ga('send', 'pageview');

</script>
````

**Comment by vanderbeam** [comment]
What's the opening tag?

**Comment by rodneystrong** [comment]
crap. i didn't format the code correctly, so the initial ````<script>```` tag didn't show up -___-)

sorry about that. it's fixed now, ready for copy/paste.

**Comment by vanderbeam** [comment]
Done

**Comment by rodneystrong** [comment]
Hmm, sorry, but I dont see this on the gh-pages url, nor do i see it on the master branch. 

Maybe you just didn't push? Either way no big deal, just please get this onto the master + gh-pages branches when you have a moment. 

Thanks!

**Comment by vanderbeam** [comment]
Oh when I saw it was self-assigned I took it out, think I must have done it wrong. Just paste it at the bottom of the page?

**Comment by rodneystrong** [comment]
Yes, please, right before the ending ````</body>```` tag

Feel free to look at our other client sites to double-check if you did it right. 

This task was self-assigned? As in I assigned it to myself and left it that way?

**Comment by vanderbeam** [comment]
Oh, no I'd added this one (it was the captcha that you self-assigned). I figured out why my pushes weren't going through... I hadn't pulled. Everything I did yesterday and a couple touch-up right now are live. The code and gallery fixes are there now.

**Comment by rodneystrong** [comment]
Gotcha. Good job on figuring out the pushing issue! 

In the future, please keep discussions about other issues in their respective issue, or at least mention that you're talking about that specific issue in order to avoid confusion. 

Thanks!
